# Generated by Django 3.0.5 on 2022-06-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_auto_20220607_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania_name', models.CharField(max_length=200)),
                ('creation_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
