# Generated by Django 3.0.5 on 2022-06-23 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('insurance', '0003_compania'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_name', models.CharField(max_length=200)),
                ('creation_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolizaRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_asegurado', models.PositiveIntegerField()),
                ('glosa', models.CharField(max_length=200)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField()),
                ('creation_date', models.DateField()),
                ('Moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Moneda')),
                ('Policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Policy')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
