# Generated by Django 3.0.5 on 2022-06-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_moneda_polizarecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polizarecord',
            old_name='Moneda',
            new_name='moneda',
        ),
        migrations.RenameField(
            model_name='polizarecord',
            old_name='Policy',
            new_name='policy',
        ),
        migrations.AlterField(
            model_name='polizarecord',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
