# Generated by Django 3.0.5 on 2022-06-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_auto_20220629_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polizarecord',
            name='moneda',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='polizarecord',
            name='policy',
            field=models.PositiveIntegerField(),
        ),
    ]
