# Generated by Django 3.0.5 on 2022-06-29 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_auto_20220629_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polizarecord',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Moneda'),
        ),
        migrations.AlterField(
            model_name='polizarecord',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Policy'),
        ),
    ]
