# Generated by Django 3.0.5 on 2022-06-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_auto_20220629_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='polizarecord',
            name='calle_unidad',
            field=models.CharField(default='Nothing', max_length=100),
        ),
        migrations.AddField(
            model_name='polizarecord',
            name='comuna_unidad',
            field=models.CharField(default='Nothing', max_length=100),
        ),
        migrations.AddField(
            model_name='polizarecord',
            name='nombre_unidad',
            field=models.CharField(default='Nothing', max_length=100),
        ),
        migrations.AddField(
            model_name='polizarecord',
            name='numero_unidad',
            field=models.CharField(default='Nothing', max_length=100),
        ),
        migrations.AddField(
            model_name='polizarecord',
            name='region_unidad',
            field=models.CharField(default='Nothing', max_length=100),
        ),
        migrations.AddField(
            model_name='polizarecord',
            name='rut_unidad',
            field=models.CharField(default='Nothing', max_length=30),
        ),
    ]
