# Generated by Django 3.0.8 on 2022-06-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_auto_20220629_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polizarecord',
            name='calle_unidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='polizarecord',
            name='comuna_unidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='polizarecord',
            name='nombre_unidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='polizarecord',
            name='numero_unidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='polizarecord',
            name='region_unidad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='polizarecord',
            name='rut_unidad',
            field=models.CharField(max_length=30),
        ),
    ]
