# Generated by Django 3.0.5 on 2022-06-29 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0011_polizarecord_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polizarecord',
            name='policy',
        ),
        migrations.AddField(
            model_name='polizarecord',
            name='Policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insurance.Policy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='polizarecord',
            name='status',
            field=models.CharField(default='Pendiente', max_length=100),
        ),
    ]
