# Generated by Django 3.0.5 on 2022-06-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0012_auto_20220629_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polizarecord',
            name='Policy',
        ),
        migrations.AddField(
            model_name='polizarecord',
            name='policy',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
