# Generated by Django 3.0.5 on 2022-06-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0013_auto_20220629_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolizaTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_unidad', models.CharField(max_length=30)),
                ('nombre_unidad', models.CharField(max_length=100)),
                ('calle_unidad', models.CharField(max_length=100)),
                ('numero_unidad', models.CharField(max_length=100)),
                ('comuna_unidad', models.CharField(max_length=100)),
                ('region_unidad', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
