# Generated by Django 3.0.5 on 2022-06-30 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_profile_pic'),
        ('insurance', '0014_polizatemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='polizatemp',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
            preserve_default=False,
        ),
    ]
