# Generated by Django 3.0.5 on 2022-07-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0015_polizatemp_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polizatemp',
            name='customer',
        ),
        migrations.AddField(
            model_name='polizatemp',
            name='CodigoExterno',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
