# Generated by Django 3.0.5 on 2022-07-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0016_auto_20220701_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='polizatemp',
            name='codunspsc',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polizatemp',
            name='nomunspsc',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
