# Generated by Django 3.0.5 on 2022-07-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0018_auto_20220703_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiciTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoExterno', models.CharField(max_length=30)),
            ],
        ),
    ]
