# Generated by Django 3.0.5 on 2022-07-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0019_licitemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='polizatemp',
            name='Descripcion',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polizatemp',
            name='FechaCierre',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='polizatemp',
            name='MontoEstimado',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polizatemp',
            name='Nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
