# Generated by Django 3.0.5 on 2022-07-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0020_auto_20220705_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polizatemp',
            name='MontoEstimado',
            field=models.FloatField(default=0),
        ),
    ]
