# Generated by Django 3.0.5 on 2022-07-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='codunspsc',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
