# Generated by Django 3.0.5 on 2022-07-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_codunspsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='codunspsc',
            field=models.PositiveIntegerField(),
        ),
    ]
