# Generated by Django 3.0.5 on 2022-07-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20220704_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='codunspsc',
            field=models.CharField(max_length=30),
        ),
    ]
