# Generated by Django 3.0.5 on 2022-07-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20220704_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='spsc',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
