# Generated by Django 3.0.5 on 2022-07-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_spsc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='spsc',
        ),
    ]
