# Generated by Django 3.0.5 on 2022-07-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_customer_spsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='codunspsc',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
