# Generated by Django 3.0.5 on 2022-07-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20220704_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='codunspsc',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
