# Generated by Django 3.0.5 on 2022-07-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20220704_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.EmailField(max_length=254),
        ),
    ]
