# Generated by Django 3.0.5 on 2022-07-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20220704_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='spsc',
            field=models.PositiveIntegerField(verbose_name='Codigo spsc'),
        ),
    ]
