# Generated by Django 3.0.5 on 2022-07-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20220704_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='spsc',
            field=models.PositiveIntegerField(),
        ),
    ]
