# Generated by Django 3.0.8 on 2022-07-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20220704_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='spsc',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
