# Generated by Django 3.0.5 on 2022-07-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20220704_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='spsc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
