# Generated by Django 3.0.8 on 2022-07-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20220705_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spsc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codunspsc', models.CharField(max_length=30)),
                ('nomunspsc', models.CharField(max_length=300)),
            ],
        ),
    ]
