# Generated by Django 3.0.5 on 2022-07-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_spsc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spsc',
        ),
    ]
